### ISSUE TITLE
오타가 난것 같아요.

### ISSUE THREAD

**Issue by ajkj** [kijin/xe-session-shield#1]
https://github.com/kijin/xe-session-shield/blob/master/session_shield.class.php#L244

$_SESSION으로 되야 하는데 $SESSION으로 되어 있는듯 합니다.

**Comment by kijin** [comment]
헐! 어쩐지 뭔가 이상해서 아침에 확인해 봐야지~ 하고 있었는데 님이 먼저 찾아주셨네요. 아직 릴리즈하지 않은 버전이라 다행입니다 ^^
