### ISSUE TITLE
파일업로드로 추정되는 경우에는 쿠키를 검증하지 않는것은 어떨까요?

### ISSUE THREAD

**Issue by ajkj** [kijin/xe-session-shield#2]
XE 3rd party 프로그램이나 회원가입폼에서 procFileUpload를 이용하지 않고 큰 용량의 파일을 저속 네트워크에서 업로드 하는경우 30초의 시간이 부족 할 수 있을 것 같습니다.

http post + content-type : multipart/form-data 인 경우(파일업로드로 추정)에는 세션 검증을 하지 않는것은 어떨까요?

**Comment by kijin** [comment]
POST + `multipart/form-data` 형식으로 들어가는 요청이 한두가지가 아닌데요... 그 두가지 조건만 보고 세션 검증을 하지 않는다면 세션 탈취 후에도 엄청나게 많은 종류의 작업을 할 수 있게 될 텐데요?

예를 들어 관리모듈에서 사이트 기본설정이나 회원정보를 수정하는 것도 모두 `multipart/form-data` 형식입니다. 평소에 `application/x-www-form-urlencoded` 형식으로 들어가는 요청들도 얼마든지 `multipart/form-data` 형식으로 바꿔서 조작할 수 있죠. 둘 중 어느 것을 사용하든 PHP에서는 똑같이 취급하니까요.

사용자의 필요에 따라 어떤 act를 예외로 할지 설정할 수 있도록 하는 방법은 가능하겠네요.

**Comment by ajkj** [comment]
답변 감사합니다. 그러면 검증을 하는 의미가 없어지겠군요. ㅠㅠ
