### ISSUE TITLE
301, 302 redirect 상황에서의 쿠키 처리

### ISSUE THREAD

**Issue by ajkj** [kijin/xe-session-shield#3]
일부 브라우저(구 버젼의 Safari) 의 경우 302 redirect에서 cookie가 set 되지 않는 문제가 있다고 하네요.

위젯에서 게시글을 누르면 302를 통해 게시글로 이동하는데, 이 경우 문제가 되지 않을까요?

https://www.google.co.kr/search?q=302+redirect&oq=302+redirect&aqs=chrome..69i57j0l5.2086j0j4&sourceid=chrome&es_sm=93&ie=UTF-8#newwindow=1&safe=off&q=302+redirect+cookie+set+safari
https://bugs.webkit.org/show_bug.cgi?id=111650
https://code.google.com/p/chromium/issues/detail?id=178201
https://code.google.com/p/chromium/issues/detail?id=150066

**Comment by ajkj** [comment]
새로운 cookie를 set하는 시점에서 모듈쪽에서 일시적인 에러가( 50x)가 날 경우에도 문제가 될 수 있을 것 같습니다. 이것까지 신경 써야 할지는 모르겠지만, 서버가 여러가지 사정으로 일시적으로 불안정해진경우(쿠키변경 로직 작동후 50X error) 로그인이 쉽게 튕길 수 있지 않을까요?

**Comment by kijin** [comment]
IE8과 일부 구버전 블랙베리에서도 가끔 그런 문제가 발생한다고 합니다. (IE8은 컴퓨터에 따라 다르다고 하네요. 저도 VM에서 이것저것 돌려보았으나 버그 재현에 실패했습니다.)

http://anvilstudios.co.za/blog/2010/08/23/session-cookies-faulty-in-ie8/

> The php function session_regenerate_id causes some IE8s to lose their cookie. This occurs if you do a redirect after logging in. What happens is that the browser redirects before it can update its cookie locally, causing the cookie SID to not match your session ID after redirecting.

이 버그를 우회하기 위해 1.0~1.1에서는 IE8에서 POST 요청을 하는 경우 세션을 갱신하지 않고 다음 GET 요청시에 갱신하도록 "예약"만 했고, 어제 수정분에서는 브라우저와 관계없이 POST 요청시 항상 예약만 하도록 변경했습니다. 대부분의 302 redirect는 POST 요청에서 발생하므로, 일단 이것으로 대부분의 경우는 커버될 것 같네요.

그렇다면 GET으로 302 redirect를 하는 경우는?

세션을 갱신해 줬는데도 불구하고 예전 세션 식별자를 사용할 경우 30초간 허용해 주는 기능이 있었죠? 오늘 아침 수정분에서 이 부분을 조금 더 강화해 보았습니다. 단지 허용해 주기만 할 뿐 아니라, 변경된 식별자를 계속해서 전송해 주는 거예요. 바보같은 브라우저가 알아들을 때까지... 대한민국의 주특기! 반복 주입식 교육!

302 redirect가 발생하면 대개 몇 초 내에 정상적인 GET 요청이 뒤따르기 때문에, 이렇게 해주면 처음에 못 알아듣더라도 새 식별자를 전달받을 기회가 충분히 주어질 것 같습니다.

50x 에러의 경우에는 애드온에서 감당할 수 있는 영역을 벗어난다고 생각됩니다. 심지어 502, 504 에러처럼 PHP단에서도 어쩔 수 없는 부분이 있죠. 그러나 세션 식별자를 갱신해 주는 시점에서 절묘하게 50x 에러가 발생한다 해도, 다음 요청에서 새 식별자를 다시 한 번 각인시켜 준다면 어느 정도는 대응이 가능하지 않을까 싶네요. 이 참에 `GRACE_PERIOD`도 30초에서 60초로 늘려줬습니다. 타임아웃 에러의 경우 대개 30초 정도에 발생하기 때문에, 타임아웃 발생시 한 번 정도는 새로고침을 시도할 여유를 주는 거죠.

**Comment by ajkj** [comment]
60초 동안의 `GRACE_PERIOD` 동안 브라우저가 말을 듣지 않으면 될때까지 set-cookie를 요청하면 대부분의 문제는 해결될것 같아요.

P.S
set-Cookie 요청을 AJAX 또는 별도의 http request 로 처리하는 방법도 생각해 보았어요. 쿠키 생성 부담을 클라이언트에 모두 맞겨버리고 클라이언트가 OK 할때까지 쿠키 재생성을 미룰 수 있다는 장점이 있는것 같긴 한데. 더러운 방법인것 같아서 안하는게 나을것 같다는 생각이 드네요.

```
<script src="https://example.com/?act=procBakeCookies"> </script>
a = jQuery.get('https://example.com/?act=procBakeCookies');
a.addEventListner('onload', function() {
jQuery.get('https://example.com/?act=procBakeCookiesFinished');
});
```
